version: '3'
services:
    dms-frontend:
        image: registry.rangdong2020.ml/dms-frontend:latest
        restart: always
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - 8081:80
